// ProyectoConVue/cotizador-prestamos-vue/src/components/Button.vue
<script setup>
    const props = defineProps(['operador','fn']);
</script>


<template>
    <button
    type="button"
    class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
    @click="fn"
    >
       {{ operador }}
    </button>
</template>

// ProyectoConReact/cotizador-prestamos-react/src/components/Button.jsx
import React from 'react'

function Button({operador, fn}) {

    return (
        <button className="h-10 w-10 flex items-center justify-center font-bold text-white text-2xl bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500"
        type="button"
        onClick={fn}
        >{operador}</button>
    )
}

export default Button
